# Copyright 2022 The Distroless Authors
# SPDX-License-Identifier: Apache-2.0

name: 'Build image with apko'
description: |
  This action build an OCI image with apko, given a config file
  and tag to use and output a tar file and does not push to a registry.

inputs:
  config:
    description: |
      The config file to use for building the image.
    default: .apko.yaml
    required: false

  tag:
    description: |
      The tag to use for building the image.
    required: true

  use-docker-mediatypes:
    description: |
      Use Docker mediatypes for building the image.
    type: boolean
    required: false

  retry-count:
    description: |
      If the command fail how many times we will retry (default: 2).
    required: false
    default: 2

runs:
  using: docker
  image: "docker://ghcr.io/chainguard-dev/apko:v0.4.0"
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
      set -o errexit

      n=0
      status=0
      until [ "$n" -ge ${{ inputs.retry-count }} ]
      do
        /ko-app/apko build \
          ${{ inputs.use-docker-mediatypes && '--use-docker-mediatypes' }} \
          ${{ inputs.config }} ${{ inputs.tag }} output.tar && status=0 && break

        status=1
        echo "apko build failed, will retry after 15 seconds..."
        n=$((n+1))
        sleep 15
      done

      echo EXIT CODE: $status
