# Copyright 2022 The Distroless Authors
# SPDX-License-Identifier: Apache-2.0

name: 'Build image with apko'
description: |
  This action build an OCI image with apko, given a config file
  and tag to use and output a tar file and does not push to a registry.

inputs:
  config:
    description: |
      The config file to use for building the image.
    default: .apko.yaml
    required: false

  keyring-append:
    description: |
      The value to pass to --keyring-append.
    default: ''

  archs:
    description: |
      The architectures to build for.
    default: ''

  source-date-epoch:
    description: |
      The UNIX timestamp to use as the source date when building an image.
      This is set as the SOURCE_DATE_EPOCH environment variable.
    default: ''

  tag:
    description: |
      The tag to use for building the image.
    required: true

  use-docker-mediatypes:
    description: |
      Use Docker mediatypes for building the image.
    type: boolean
    required: false

  debug:
    description: |
      Enable debug logging.
    type: boolean
    required: false
    default: false

runs:
  using: docker
  image:  "docker://ghcr.io/chainguard-dev/apko:canary"
  entrypoint: /bin/sh
  args:
    - '-c'
    - |
      set -o errexit
      [ -n "${{ inputs.source-date-epoch }}" ] && export SOURCE_DATE_EPOCH='${{ inputs.source-date-epoch }}'
      [ -n "${{ inputs.keyring-append }}" ] && keys="-k ${{ inputs.keyring-append }}"
      [ -n "${{ inputs.archs }}" ] && archs="--arch ${{ inputs.archs }}"
      /ko-app/apko build \
        ${{ inputs.use-docker-mediatypes && '--use-docker-mediatypes' }} \
        ${{ inputs.debug && '--debug' }} \
        ${{ inputs.config }} ${{ inputs.tag }} output.tar $keys $archs
      echo EXIT CODE: $?
